In [7]:
from gensim.models import Word2Vec,KeyedVectors
import gensim.downloader as api

this model is trained over the google news data

the dimesion of this model(number of neuron in hidden layer)=300

news--> crimial

In [8]:
#skim gram
model = api.load("word2vec-google-news-300")

In [10]:
model["sunny"]

array([ 1.59179688e-01,  1.07910156e-01,  3.71093750e-02,  1.61132812e-01,
        3.02734375e-01, -3.35937500e-01, -3.83300781e-02, -1.32751465e-03,
       -8.69140625e-02,  2.25585938e-01,  2.23388672e-02,  1.35742188e-01,
       -1.04003906e-01,  1.73828125e-01,  5.46875000e-02,  1.13769531e-01,
       -1.53320312e-01,  2.29492188e-01,  1.13769531e-01,  1.61132812e-02,
       -1.46484375e-01,  5.07812500e-01, -1.08886719e-01, -1.59179688e-01,
       -9.37500000e-02, -6.64062500e-02,  1.90429688e-01,  2.49023438e-01,
       -1.08398438e-01,  2.00195312e-01, -2.19726562e-01,  8.83789062e-02,
        4.98046875e-02,  4.27246094e-02, -3.02734375e-01, -1.64062500e-01,
       -9.86328125e-02, -2.61718750e-01,  1.49414062e-01,  2.12890625e-01,
        2.38281250e-01, -1.50390625e-01,  1.82617188e-01,  1.18408203e-02,
        1.85546875e-02, -1.41601562e-01, -1.41601562e-01,  3.14941406e-02,
       -2.50000000e-01,  2.55859375e-01,  2.53906250e-01,  3.69140625e-01,
        4.43359375e-01,  

In [11]:
len(model["sunny"])

300

In [56]:
model["i am sunny"]

KeyError: "Key 'i am sunny' not present"

In [13]:
model["men"]

array([-4.78515625e-02,  1.66992188e-01,  7.81250000e-02,  2.10571289e-03,
        2.25585938e-01, -2.25585938e-01, -2.09960938e-01, -3.73535156e-02,
       -1.85546875e-02,  1.94335938e-01, -3.00292969e-02, -1.77734375e-01,
        5.20019531e-02,  1.33789062e-01, -1.13769531e-01,  1.10351562e-01,
       -3.27148438e-02,  2.89916992e-03,  9.88769531e-03,  9.27734375e-02,
       -2.19726562e-01, -2.47802734e-02, -8.59375000e-02, -2.67578125e-01,
       -2.51464844e-02, -2.55859375e-01, -1.61132812e-01,  2.53906250e-01,
        5.24902344e-02, -1.00097656e-02,  1.82617188e-01,  7.61718750e-02,
       -1.60980225e-03, -3.10058594e-02, -3.32031250e-02,  1.81640625e-01,
       -3.88183594e-02, -1.83593750e-01, -8.64257812e-02,  2.20703125e-01,
       -7.11059570e-03,  8.60595703e-03,  1.73828125e-01, -9.27734375e-02,
        1.25000000e-01, -1.28906250e-01, -4.85839844e-02, -1.21093750e-01,
        8.00781250e-02,  1.05957031e-01,  1.42578125e-01,  6.78710938e-02,
        6.29882812e-02, -

In [14]:
model.most_similar("man")

[('woman', 0.7664012908935547),
 ('boy', 0.6824871301651001),
 ('teenager', 0.6586930155754089),
 ('teenage_girl', 0.6147903203964233),
 ('girl', 0.5921714305877686),
 ('suspected_purse_snatcher', 0.571636438369751),
 ('robber', 0.5585119128227234),
 ('Robbery_suspect', 0.5584409832954407),
 ('teen_ager', 0.5549196600914001),
 ('men', 0.5489763021469116)]

In [17]:
model.most_similar("golf")

[('golfing', 0.8088686466217041),
 ('golfers', 0.7460012435913086),
 ('golfer', 0.7288370132446289),
 ('Golf', 0.725327730178833),
 ('golf_courses', 0.7062751054763794),
 ('Golf_Club', 0.6499657034873962),
 ('PGA', 0.641076385974884),
 ('Golf_Course', 0.6299023628234863),
 ('Kaluhyat', 0.6198312640190125),
 ('Golfers', 0.6177543997764587)]

In [18]:
model.similarity("man","woman")

0.76640123

In [19]:
model.similarity("man","python")

0.2097966

In [57]:
model.similarity("man","men")

0.5489763

In [29]:
model.similarity("delighted","ecstatic")

0.6400829

In [31]:
model.similarity('python','snake')

0.66062933

In [34]:
model.similarity('overcast','cloudy')

0.66257375

In [35]:
model.similarity('sunny','Sunny')

0.43010473

In [40]:
model.doesnt_match(["PHP", "FOOD", "India", "JAVA","DOG","C++","NBA"])

'NBA'

In [41]:
vec=model['king'] - model['man'] + model['woman']

In [42]:
model.most_similar([vec])

[('king', 0.8449392318725586),
 ('queen', 0.7300517559051514),
 ('monarch', 0.645466148853302),
 ('princess', 0.6156251430511475),
 ('crown_prince', 0.5818676352500916),
 ('prince', 0.5777117609977722),
 ('kings', 0.5613663792610168),
 ('sultan', 0.5376775860786438),
 ('Queen_Consort', 0.5344247817993164),
 ('queens', 0.5289887189865112)]

## average wrod2vec

In [43]:
sentence = " I love machine learning"

sentece -> vector?

averge Word2Vec

first -> create a vector for each word in the sentence

then -> take the average of all the vectors to get a single vector representation for the entire sentence   

SyntaxError: invalid syntax (3084447811.py, line 5)

In [47]:
sentence = " I loVe Machine leaRning"

In [58]:
sentence.lower().split()

['i', 'love', 'machine', 'learning']

In [48]:
words = sentence.lower().split()

In [59]:
word_vectors = []

In [63]:
for word in words:
    print(word)
    word_vectors.append(model[word])
    

i
love
machine
learning


In [64]:
word_vectors

['i',
 'love',
 'machine',
 'learning',
 'i',
 'love',
 'machine',
 'learning',
 array([-2.25585938e-01, -1.95312500e-02,  9.08203125e-02,  2.37304688e-01,
        -2.92968750e-02,  9.32617188e-02, -5.88378906e-02, -4.10156250e-02,
         5.22460938e-02,  2.00195312e-02, -3.44238281e-02, -2.91015625e-01,
        -2.61718750e-01, -1.90429688e-01,  3.85742188e-02,  8.30078125e-03,
         3.14941406e-02,  7.47070312e-02,  1.14746094e-01,  1.24511719e-02,
        -2.11914062e-01,  1.28906250e-01,  2.55859375e-01,  1.08886719e-01,
        -7.03125000e-02,  1.60156250e-01, -4.00390625e-01, -1.16699219e-01,
        -3.22265625e-02, -6.73828125e-02,  1.55273438e-01,  1.25000000e-01,
        -6.22558594e-02,  3.56445312e-02, -1.79687500e-01,  1.58203125e-01,
        -2.53906250e-01,  1.74804688e-01, -1.18164062e-01, -2.19726562e-03,
         1.49536133e-02, -5.71289062e-02,  2.39257812e-01,  1.36718750e-01,
         1.47460938e-01,  7.08007812e-02,  1.72851562e-01, -2.38281250e-01,
        

In [65]:
import numpy as np
sentence_vector =  np.mean(word_vectors,axis=0)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (12,) + inhomogeneous part.

In [54]:
sentence_vector

NameError: name 'sentence_vector' is not defined

In [31]:
sentence_vector.shape

(300,)

In [ ]:
word2vec -> every word into the KeyedVectors

avg word2vec -> every sentence into a vector

now this technique is old, 

will see the sota(transformer based tech in next class)